language: node_js

node_js:
  - '8'

sudo: false

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g npm

install:
  - npm install

before_script:
  - npm install --save-dev gulp del typescript gulp-typescript

script: 
  - gulp